# Writes web/.env.local from your Supabase keys (interactive; input is hidden).
# Run from PowerShell:
#   cd "C:\Users\User\Desktop\Monza CRM\MONZA-CRM\web"
#   .\scripts\set-supabase-env.ps1

$ErrorActionPreference = "Stop"
$webRoot = Split-Path -Parent $PSScriptRoot
$envPath = Join-Path $webRoot ".env.local"

Write-Host ""
Write-Host "MONZA CRM — Supabase env setup" -ForegroundColor Cyan
Write-Host "Project URL (default: https://okxpsvukzjjubinhamek.supabase.co)" -ForegroundColor Gray
$url = Read-Host "Press Enter to keep default, or paste your Project URL"
if ([string]::IsNullOrWhiteSpace($url)) {
  $url = "https://okxpsvukzjjubinhamek.supabase.co"
}

Write-Host ""
Write-Host "Paste your PUBLISHABLE key (sb_publishable_...) or legacy anon JWT — hidden:" -ForegroundColor Yellow
$anonSecure = Read-Host -AsSecureString
if ($null -eq $anonSecure -or $anonSecure.Length -eq 0) {
  Write-Error "No client key entered. Exiting."
}
$anonPtr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($anonSecure)
try {
  $anon = [Runtime.InteropServices.Marshal]::PtrToStringAuto($anonPtr)
} finally {
  [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($anonPtr)
}

Write-Host ""
Write-Host "Paste your SECRET key (sb_secret_...) or legacy service_role — hidden:" -ForegroundColor Yellow
$svcSecure = Read-Host -AsSecureString
if ($null -eq $svcSecure -or $svcSecure.Length -eq 0) {
  Write-Error "No server key entered. Exiting."
}
$svcPtr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($svcSecure)
try {
  $service = [Runtime.InteropServices.Marshal]::PtrToStringAuto($svcPtr)
} finally {
  [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($svcPtr)
}

$anon = $anon.Trim()
$service = $service.Trim()
$url = $url.Trim()

if ($anon -match "your_anon_key_here" -or $service -match "your_service_role_key_here") {
  Write-Error "Those look like placeholders. Paste the real keys from Supabase → Settings → API Keys."
}

$content = @"
# Supabase Configuration (generated by scripts/set-supabase-env.ps1)
NEXT_PUBLIC_SUPABASE_URL=$url
NEXT_PUBLIC_SUPABASE_ANON_KEY=$anon
SUPABASE_SERVICE_ROLE_KEY=$service

# Web Push (optional — generate with: npx web-push generate-vapid-keys)
NEXT_PUBLIC_VAPID_PUBLIC_KEY=your_vapid_public_key
VAPID_PRIVATE_KEY=your_vapid_private_key
"@

Set-Content -Path $envPath -Value $content -Encoding UTF8
Write-Host ""
Write-Host "Saved: $envPath" -ForegroundColor Green
Write-Host "Next: cd web && npm run dev" -ForegroundColor Gray
Write-Host ""
